name: "ship-management"

services:
 ship-management:
  image: ship-management:v0.0.1
  container_name: ship-management
  restart: always
  network_mode: bridge
  ports:
    - 8888:8888
  environment:
    - LOG_LEVEL=info
    - ADDR=:8888
    - SQL_SERVER_DSN=sqlserver://sa:smart_ship123..@172.31.126.33:1433?database=ISM_Vsl_9977551&encrypt=disable
